
spring:
  application:
    name: list-customer-2-feign
  kafka:
     bootstrap-servers: 114.55.66.218:9092
     consumer:
       group-id: group0
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.apache.kafka.common.serialization.StringSerializer
       enable-auto-commit: false #关闭自动提交offset
  rabbitmq:
      host: 114.55.66.218
      port: 5672
      username: root
      password: root
      listener:
        simple:
          acknowledge-mode: manual # 手动确认消息
          retry:
            enabled: true
            multiplier: 2 # 乘子
            max-attempts: 5 # 最大重试次数
            initial-interval: 3000 # 第一次和第二次之间的重试间隔，后面的用乘子计算 重试间隔为：3s 6s 12s 24s
            max-interval: 3600000 # 最大重试时间
info:
  auth: list
  app.name: customer2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8011
feign:
  hystrix:
    enabled: true
