spring:
  application:
    name: list-provider-1
  redis:
    host: 114.55.66.218
    # Redis服务器连接端口
    port: 6379
    password: tiger-redis
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #最大空闲连接
        max-idle : 100
        #最小空闲连接
        min-idle : 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 30000
     #默认是索引为0的数据库
    database: 0
  kafka:
    bootstrap-servers: 114.55.66.218:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


info:
  auth: list
  app.name: provider1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka



